### ISSUE TITLE
I got an error

### ISSUE THREAD

**Issue by ghost** [okfn/dataproxy#23]
I wanted to see the detail of my own dataset,
But I got an error:

 This resource can not be previewed at the moment. Click here for more information.

Could not load preview: DataProxy returned an error (Data transformation failed. error: An error occured while connecting to the server: Unable to fetch URL: http://MyURL/xxx.csv)

What happened? and What should I do? :(

**Comment by johnxue2013** [comment]
@rgrp i think he is right, url starts with http://localhost,tha means,dataproxy won'n able to access it.
